/** Duration (ms) for which form error banners remain visible before auto-dismissal. */
export const ERROR_DISPLAY_DURATION_MS = 5000;

/** localStorage key for the auth JWT. */
export const AUTH_TOKEN_KEY = "crm_auth_token";

/** Base URL for all API requests. */
export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL ?? "/api";

/** External business card OCR API endpoint. */
export const CARD_SCAN_API_URL = import.meta.env.VITE_CARD_SCAN_API_URL || "/ocr/extract";

/** Roles a super admin or admin can assign when creating/editing an employee. */
export const MANAGEABLE_ROLES: Array<"ADMIN" | "EMPLOYEE"> = [
  "ADMIN",
  "EMPLOYEE",
];

/** Human-readable labels for each role. */
export const ROLE_LABELS: Record<string, string> = {
  SUPER_ADMIN: "Super Admin",
  ADMIN: "Admin",
  EMPLOYEE: "Employee",
};

export const ROLE_HIERARCHY = {
  EMPLOYEE: 1,
  ADMIN: 2,
  SUPER_ADMIN: 3,
} as const;

export const USERNAME_MIN_LENGTH = 3;
export const USERNAME_MAX_LENGTH = 50;
export const PASSWORD_MIN_LENGTH = 8;

export const DASHBOARD_NAV_ITEMS = [
  { label: "Users", to: "/super-admin/dashboard/users" },
  { label: "Profile", to: "/super-admin/dashboard/profile" },
] as const;

export const ACCESS_TYPE_LABELS: Record<string, string> = {
  READ_WRITE: "Read · Write",
  READ_ONLY: "Read Only",
};

export const OPPORTUNITY_STAGES = [
  "LEAD",
  "QUALIFIED_LEAD",
  "NEEDS_ANALYSIS",
  "PROPOSAL_DEMO",
  "NEGOTIATION",
  "CLOSED_WON",
  "ONBOARDING",
  "ACTIVE_RETENTION",
  "CHURNED_CLOSED_LOST",
] as const;

export const OPPORTUNITY_STAGE_LABELS: Record<
  (typeof OPPORTUNITY_STAGES)[number],
  string
> = {
  LEAD: "Lead",
  QUALIFIED_LEAD: "Qualified Lead",
  NEEDS_ANALYSIS: "Needs Analysis",
  PROPOSAL_DEMO: "Proposal / Demo",
  NEGOTIATION: "Negotiation",
  CLOSED_WON: "Closed Won",
  ONBOARDING: "Onboarding",
  ACTIVE_RETENTION: "Active Retention",
  CHURNED_CLOSED_LOST: "Churned / Closed Lost",
};

export const QUICK_MESSAGE_PLATFORMS = [
  "WHATSAPP",
  "INSTAGRAM",
  "LINKEDIN",
  "X",
  "FACEBOOK",
  "SMS",
] as const;

export const QUICK_MESSAGE_PLATFORM_LABELS: Record<
  (typeof QUICK_MESSAGE_PLATFORMS)[number],
  string
> = {
  WHATSAPP: "WhatsApp",
  INSTAGRAM: "Instagram",
  LINKEDIN: "LinkedIn",
  X: "X",
  FACEBOOK: "Facebook",
  SMS: "SMS",
};

export const COUNTRIES: string[] = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo (DRC)",
  "Congo (Republic)",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];
